site_name: dl4seas

# mkdocs.yml
theme:
  name: "material"
  palette:
    primary: lime
  features:
    - instant
    - navigation.expand

plugins:
  - search
  - mkdocstrings

nav:
    - Home: index.md
    - Installation: installation.md
    - Code Reference:
        - utils: utils-reference.md

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/nfauchereau
    - icon: fontawesome/brands/github
      link: https://github.com/nicolasfauchereau